CREATE TABLE IF NOT EXISTS ACCOUNT (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  username VARCHAR(250) NOT NULL,
  password VARCHAR(250) NOT NULL,
  token INT DEFAULT NULL,
  gbp INT NOT NULL,
  btc INT NOT NULL
);

CREATE TABLE IF NOT EXISTS ORDERS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(250) NOT NULL,
  orderAction VARCHAR(250) NOT NULL,
  price INT NOT NULL,
  volume INT,
  orderTime TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS TRADE (
  id INT AUTO_INCREMENT PRIMARY KEY,
  buyer VARCHAR(250) NOT NULL,
  seller VARCHAR(250) NOT NULL,
  price INT NOT NULL,
  volume INT NOT NULL,
  tradetime TIMESTAMP NOT NULL
);