CREATE TABLE IF NOT EXISTS ACCOUNT (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  username VARCHAR(250) NOT NULL,
  password VARCHAR(250) NOT NULL,
  token INT DEFAULT NULL,
  gbp INT NOT NULL,
  btc INT NOT NULL
);
